### PR TITLE
Keep traceback when handling an error

### PR DESCRIPTION
**Pull request by skritch**
A raw `raise` will reraise the last caught exception, preserving the traceback.

I'd prefer to do `import sys; exc_info = sys.exc_info(); ... raise exc_info[0], exc, exc_info[2]` but it doesn't appear valid in python 3, while the pure `raise` seems to work.

As demonstrated by:
```
def raiser():
    raise ValueError

def handle_exc(e):
    # do stuff
    raise 

def try_it():
    try:
        raiser()
    except Exception, e:
        handle_exc(e)

>>> try_it()
Traceback (most recent call last):
  File "/Users/samk/Library/Preferences/IntelliJIdea2017.1/scratches/scratch.py", line 19, in <module>
    try_it()
  File "/Users/samk/Library/Preferences/IntelliJIdea2017.1/scratches/scratch.py", line 17, in try_it
    handle_exc(e)
  File "/Users/samk/Library/Preferences/IntelliJIdea2017.1/scratches/scratch.py", line 15, in try_it
    raiser()
  File "/Users/samk/Library/Preferences/IntelliJIdea2017.1/scratches/scratch.py", line 7, in raiser
    raise ValueError
ValueError
```
With `raise e` instead of `raise`, the final `raiser` line does not appear.

### CODE REVIEW

**Comment by rozumem** [comment]
So doing a:

`raise sys.exc_info()`

is not valid Python 3?

**Comment by skritch** [comment]
It's not. python3 requires that the `raise` arg inherit from `BaseException`.

**Comment by rozumem** [comment]
👍

**Comment by skritch** [comment]
This isn't actually the right place to PR this.

**Pull request closed without merging**
